name: Format and Lint

on:
  push:
    branches:
      - linting_rumi
  pull_request:
    branches:
      - linting_rumi

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff

      - name: Format
        run: black .

      - name: Lint
        run: ruff check . --fix

      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Auto-fix linting and formatting issues" || echo "No changes to commit"
          git push origin linting_rumi
